### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by jcpy-256** [KingGugu/TiCoSeRec#3]
在data_augmention.py中的Insert类中，使用np.argsort似乎并没有找到时间间隔最大和最小的item对应的索引(插入的位置)
![N~C{F%BQ Y)SLF6}YR%R3HJ](https://user-images.githubusercontent.com/72605189/229342600-e7ecace1-a156-4135-b697-6089c84482e9.png)
![image](https://user-images.githubusercontent.com/72605189/229342540-395f3cd9-2007-49d2-bf59-a1835e0225f4.png)

**Comment by KingGugu** [comment]
你好，minimum的代码可以忽略，我们以maximum下的代码为例。首先请你仔细阅读这一句话：
**First sort from large to small, and then return the original index value by sorting. 
The larger the value, the smaller the index value.**
`diff_sorted = np.argsort(time_diffs)[::-1]`

代码首先会对时间间隔从大到小进行排序，之后返回重新排序后的index，注意，这里返回的是index，而不是时间间隔实际的值。时间间隔越大，那么index的值就会越小。以你的测试代码中，时间间隔为`[2,0,1,5,6,-1]`为例（正常情况下时间间隔不会为-1）。代码返回diff_sort是`[4,3,0,2,1,5]`。在时间间隔中，最大的间隔为6，它的原始index为4，那么在diff_sort中，4就被排到了首个，它在diff_sort中的index是0，以此类推。minimum中也是相同的道理，只不过排序是反过来的。

**Comment by jcpy-256** [comment]
感谢您的答复！最大间隔为6，对应index为4，在下面的for循环中取出的insert_idx=[2, 4]但是index=2对应的时间间隔为1而不是5.请问这是为什么呢？按照文章的意思似乎是insert_idx=[4,3]

**Comment by KingGugu** [comment]
我刚仔细检查了一下，这里确实是代码实现错误了。正确的应该是：
`temp = diff_sorted[i]`

`diff_sorted.index(i)`应该是之前某个实现版本的，我在上传时可能存在失误，感谢你提出的issue，我晚些时候会完善这里。

**Comment by jcpy-256** [comment]
好的，感谢您的回复。

**Comment by KingGugu** [comment]
代码已经更新。再次表示感谢！
