### ISSUE TITLE
The question about the code

### ISSUE THREAD

**Issue by zyx1017** [KingGugu/TiCoSeRec#4]
Hello!  
Notice that you mention  implement other models in RecBole 1.0 and 2.0 in your paper.
Can you share that part of the code?

**Comment by KingGugu** [comment]
Thanks for your attention. The models we use have been implemented in RecBole 1.0 and 2.0, and you can directly follow the tutorial to run them.
RecBole 1.0 : https://github.com/RUCAIBox/RecBole
RecBole 2.0 DA : https://github.com/RUCAIBox/RecBole-DA

**Comment by zyx1017** [comment]
@KingGugu 
The paper says to turn off the default data enhancement operation of Burroughs, do you know how to turn it off?

**Comment by KingGugu** [comment]
Please refer to these issues in RecBole:
https://github.com/RUCAIBox/RecBole/issues/1069
https://github.com/RUCAIBox/RecBole/issues/1298
https://github.com/RUCAIBox/RecBole/issues/1624

**Comment by zyx1017** [comment]
@KingGugu 
I couldn't find a solution very well. Can I refer to your code?

**Comment by KingGugu** [comment]
The code for RecBole that was running at that time has been removed from the server, so I am currently unable to provide it. If there are issues with the use of RecBole, perhaps you can raise an issue with the author. Thank you!

**Comment by zyx1017** [comment]
@KingGugu 
Hi, do you remember what loss function was used when you used RecBole to reproduce those baseline models, like SASRec? I found that using BPR as the value of the loss function gives much smaller results than using CE as the loss function.

**Comment by KingGugu** [comment]
We follow the default parameters of RecBole and make modifications based on the parameters reported in the paper. 

Collaborative filtering models generally use BPR, and sequential models generally use CE. For SASRec Use CE as a loss function.

Regarding the issue with RecBole, you may submit an issue under its repositories.
