### ISSUE TITLE
你好，数据集中好像没有看到有使用时间戳信息?

### ISSUE THREAD

**Issue by zyx1017** [KingGugu/TiCoSeRec#5]

**Comment by KingGugu** [comment]
你好，感谢你对我们工作的关注。

xxx_time_xxx_rank.txt中就是时间戳信息。

**Comment by zyx1017** [comment]
data_process中是将数据集处理为相应训练数据的工具吗？我想在新的数据集上尝试

**Comment by zyx1017** [comment]
你好，没太看懂如何利用data_process里的工具处理自己的数据集，能提供一个大概的流程吗？

**Comment by KingGugu** [comment]
split是实证研究用的，用于划分数据集得到均匀和非均匀的子集。

另外三个文件从文件名可以看出，是将数据集文件转换为.csv格式和.txt格式，实际处理时可能需要根据你的数据集对代码进行适当的修改。
