### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by froverkkk** [KingGugu/TiCoSeRec#6]
你好，在data_augmentation_time.py中，计算方差的是get_var这个函数，我看论文里都是在说std标准差，是否是有问题，另外我想请教下，Figure1中的std是怎么计算的，以及Figure3中的（a）,我按照公式计算，结果不一样
![1](https://github.com/KingGugu/TiCoSeRec/assets/145466655/137bca65-6597-410d-a2df-e11f976bbce1)

**Comment by KingGugu** [comment]
同学您好，


非常感谢你对我们工作的关注！


关于图1和图3的计算问题，确实存在错误，我们会在后续的版本进行修订，感谢你发现并指出了它。


关于论文中的std（Standard Deviation）就是指标准差和代码中的实现问题。因为实际上在计算算子操作的位置或是否使序列更均匀时，只需要比较大小，所以全部使用标准差和全部使用方差并不会对结果产生影响（大于0的数，数本身越大平方就越大，开根也是同理）。我们也会在以后的工作中注意保持论文和代码实现的完全一致，以免对读者产生误导。



如果还有其他疑问，欢迎联系。祝科研顺利！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KingGugu/TiCoSeRec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月15日(星期五) 下午3:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[KingGugu/TiCoSeRec] 代码问题 (Issue #6)





 
你好，在data_augmentation_time.py中，计算方差的是get_var这个函数，我看论文里都是在说std标准差，是否是有问题，另外我想请教下，Figure1中的std是怎么计算的，以及Figure3中的（a）,我按照公式计算，结果不一样
 1.PNG (view on web)
